"""
train_with_ocr_features.py — Stacking Meta-Learner for OCR Spatial + TVC Features.

Strategy:
  The existing XGBoost models (xgb_label_model, xgb_source_model) are kept FROZEN.
  A lightweight meta-learner is trained on top of:
    1. Base model's probability outputs (class probabilities)
    2. New TVC numeric features (tvc_brand_spoofed, tvc_fuzzy_score, etc.)
    3. New spatial OCR TF-IDF vectors (ocr_header_text, ocr_footer_text)

  This preserves all existing model knowledge while adding new visual signals.

Prerequisites:
  The training CSV must contain the new columns generated by the updated pipeline.
  Run the pipeline over training data FIRST to populate:
    ocr_header_text, ocr_body_text, ocr_footer_text,
    tvc_brand_detected, tvc_detected_brand, tvc_domain_match,
    tvc_fuzzy_score, tvc_brand_spoofed,
    ocr_header_word_count, ocr_footer_word_count, ocr_total_word_count

Usage:
    cd c:\\Users\\SATWIK\\Documents\\Phishing
    python -m scripts.train_with_ocr_features
"""

import os
import sys
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack, csr_matrix
from xgboost import XGBClassifier
import joblib
import warnings

warnings.filterwarnings("ignore", category=UserWarning, module="sklearn")

# Fix Windows console encoding for emoji output
if sys.platform.startswith("win"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ==========================
# Paths
# ==========================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.dirname(SCRIPT_DIR)
DATA_DIR   = os.path.join(ROOT_DIR, "data", "training")
MODELS_DIR = os.path.join(ROOT_DIR, "models")
META_DIR   = os.path.join(MODELS_DIR, "meta")  # Meta-learner artifacts

os.makedirs(META_DIR, exist_ok=True)

TRAINING_CSV = os.path.join(DATA_DIR, "training_dataset_features.csv")

# ==========================
# 1. Load Frozen Base Models
# ==========================
print("=" * 60)
print("🧱 STAGE 1: Loading frozen base models")
print("=" * 60)

base_label_model  = joblib.load(os.path.join(MODELS_DIR, "xgb_label_model.joblib"))
base_source_model = joblib.load(os.path.join(MODELS_DIR, "xgb_source_model.joblib"))
base_feature_cols = joblib.load(os.path.join(MODELS_DIR, "feature_columns.joblib"))
base_scaler       = joblib.load(os.path.join(MODELS_DIR, "scaler.joblib"))
base_imputer      = joblib.load(os.path.join(MODELS_DIR, "imputer.joblib"))
le_label          = joblib.load(os.path.join(MODELS_DIR, "label_encoder_label.joblib"))
source_classes    = joblib.load(os.path.join(MODELS_DIR, "source_classes.joblib"))

# TF-IDF models (base)
tfidf_asn = None
if os.path.exists(os.path.join(MODELS_DIR, "tfidf_asn.joblib")):
    tfidf_asn = joblib.load(os.path.join(MODELS_DIR, "tfidf_asn.joblib"))

tfidf_ocr = None
if os.path.exists(os.path.join(MODELS_DIR, "tfidf_ocr.joblib")):
    tfidf_ocr = joblib.load(os.path.join(MODELS_DIR, "tfidf_ocr.joblib"))

print(f"  ✅ Base label model loaded ({len(le_label.classes_)} classes)")
print(f"  ✅ Base source model loaded ({len(source_classes)} classes)")
print(f"  ✅ Base feature columns: {len(base_feature_cols)}")

# ==========================
# 2. Load Training Data
# ==========================
print("\n" + "=" * 60)
print("📂 STAGE 2: Loading training data")
print("=" * 60)

data = pd.read_csv(TRAINING_CSV)
print(f"  Loaded {len(data)} rows × {data.shape[1]} columns")

# Check which new columns are available
NEW_NUMERIC_COLS = [
    "tvc_brand_detected", "tvc_domain_match", "tvc_fuzzy_score",
    "tvc_brand_spoofed", "ocr_header_word_count", "ocr_footer_word_count",
    "ocr_total_word_count",
]
NEW_TEXT_COLS = ["ocr_header_text", "ocr_footer_text"]

available_numeric = [c for c in NEW_NUMERIC_COLS if c in data.columns]
available_text    = [c for c in NEW_TEXT_COLS if c in data.columns]
missing_cols      = [c for c in NEW_NUMERIC_COLS + NEW_TEXT_COLS if c not in data.columns]

if missing_cols:
    print(f"\n  ⚠️  Missing columns (will be zero-filled): {missing_cols}")
    print("  � TIP: Re-run the pipeline over training data to generate these columns.")
    print("       python main_controller.py   (with training URLs as input)")
    for col in missing_cols:
        if col in NEW_NUMERIC_COLS:
            data[col] = 0
        else:
            data[col] = ""
    available_numeric = NEW_NUMERIC_COLS
    available_text = NEW_TEXT_COLS

print(f"  ✅ New numeric features: {available_numeric}")
print(f"  ✅ New text features: {available_text}")

# ==========================
# 3. Generate Base Model Predictions (frozen)
# ==========================
print("\n" + "=" * 60)
print("🔮 STAGE 3: Generating base model predictions (frozen)")
print("=" * 60)

# Reconstruct the base feature matrix exactly as the pipeline does
X_base_raw = data[base_feature_cols].copy()

# Handle booleans → integers for the base model
for col in X_base_raw.columns:
    if X_base_raw[col].dtype == bool:
        X_base_raw[col] = X_base_raw[col].astype(int)

X_base_imputed = base_imputer.transform(X_base_raw)
X_base_scaled  = base_scaler.transform(X_base_imputed)

# Add text TF-IDF features (same as original training)
base_text_features = []
if tfidf_asn and "asn_org" in data.columns:
    data["asn_org"] = data["asn_org"].fillna("")
    base_text_features.append(tfidf_asn.transform(data["asn_org"]))

if tfidf_ocr and "ocr_text" in data.columns:
    data["ocr_text"] = data["ocr_text"].fillna("")
    base_text_features.append(tfidf_ocr.transform(data["ocr_text"]))

if base_text_features:
    X_base_full = hstack([csr_matrix(X_base_scaled)] + base_text_features).tocsr()
else:
    X_base_full = csr_matrix(X_base_scaled)

# Get probability predictions from base models
print("  Predicting with base label model...")
base_label_probs = base_label_model.predict_proba(X_base_full)
print(f"    → Shape: {base_label_probs.shape} (probabilities for {base_label_probs.shape[1]} classes)")

# Source model was trained on a subset (domains with >= 5 occurrences)
# For meta-learner, we use label model probs for all rows
print(f"  ✅ Base predictions generated for {len(data)} rows")

# ==========================
# 4. Build Meta-Feature Matrix
# ==========================
print("\n" + "=" * 60)
print("🏗️  STAGE 4: Building meta-feature matrix")
print("=" * 60)

# 4a. Base model probability outputs (frozen)
meta_features_list = [base_label_probs]
feature_names = [f"base_prob_{cls}" for cls in le_label.classes_]
print(f"  📊 Base model probs: {base_label_probs.shape[1]} features")

# 4b. New numeric/boolean TVC features
new_numeric_df = data[available_numeric].copy()
for col in new_numeric_df.columns:
    if new_numeric_df[col].dtype == bool:
        new_numeric_df[col] = new_numeric_df[col].astype(int)
    new_numeric_df[col] = new_numeric_df[col].fillna(0)

meta_features_list.append(new_numeric_df.values)
feature_names += available_numeric
print(f"  � New numeric features: {len(available_numeric)}")

# 4c. New TF-IDF text features (OCR header + footer zones)
tfidf_models = {}

for col, max_feats, label in [
    ("ocr_header_text", 200, "OCR Header"),
    ("ocr_footer_text", 100, "OCR Footer"),
]:
    if col in data.columns and data[col].notna().sum() > 0:
        data[col] = data[col].fillna("")
        tfidf = TfidfVectorizer(max_features=max_feats)
        X_tfidf = tfidf.fit_transform(data[col])
        meta_features_list.append(X_tfidf.toarray())
        feature_names += [f"tfidf_{col}_{i}" for i in range(X_tfidf.shape[1])]
        tfidf_models[col] = tfidf
        joblib.dump(tfidf, os.path.join(META_DIR, f"tfidf_{col}.joblib"))
        print(f"  � {label} TF-IDF: {X_tfidf.shape[1]} features")

# Combine all meta-features into a single matrix
X_meta = np.hstack(meta_features_list)
print(f"\n  ✅ Final meta-feature matrix: {X_meta.shape}")
print(f"  ✅ Total features: {len(feature_names)}")

# ==========================
# 5. Impute & Scale Meta-Features
# ==========================
print("\n" + "=" * 60)
print("⚙️  STAGE 5: Imputing and scaling meta-features")
print("=" * 60)

meta_imputer = SimpleImputer(strategy="median")
X_meta_imputed = meta_imputer.fit_transform(X_meta)

meta_scaler = StandardScaler()
X_meta_scaled = meta_scaler.fit_transform(X_meta_imputed)

print(f"  ✅ Imputed and scaled: {X_meta_scaled.shape}")

# ==========================
# 6. Prepare Targets
# ==========================
y_label = le_label.transform(data["Cooresponding CSE"])

# ==========================
# 7. Train Meta-Learner
# ==========================
print("\n" + "=" * 60)
print("🚀 STAGE 6: Training meta-learner")
print("=" * 60)

class_counts = pd.Series(y_label).value_counts()
if len(class_counts) == 2:
    scale_pos_weight = class_counts[0] / class_counts[1]
else:
    scale_pos_weight = 1.0

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [3, 4, 6],
    "learning_rate": [0.05, 0.1, 0.2],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0],
    "min_child_weight": [1, 5],
    "gamma": [0, 0.1],
    "reg_lambda": [1, 5],
}

meta_xgb = XGBClassifier(
    objective="multi:softprob" if len(np.unique(y_label)) > 2 else "binary:logistic",
    eval_metric="mlogloss",
    random_state=42,
    scale_pos_weight=scale_pos_weight,
    use_label_encoder=False,
)

min_class_count = class_counts.min()
n_splits = 5 if min_class_count >= 5 else 3

cv = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

search = RandomizedSearchCV(
    estimator=meta_xgb,
    param_distributions=param_grid,
    n_iter=20,
    scoring="f1_macro",
    n_jobs=-1,
    cv=cv,
    verbose=1,
    random_state=42,
)

print(f"  Running RandomizedSearchCV (n_iter=20, cv={n_splits})...")
search.fit(X_meta_scaled, y_label)

print(f"\n  🏆 Best Params: {search.best_params_}")
print(f"  ✅ CV F1 Macro: {search.best_score_:.4f}")

meta_model = search.best_estimator_

# ==========================
# 8. Feature Importance
# ==========================
print("\n" + "=" * 60)
print("📊 STAGE 7: Feature importance (top 15)")
print("=" * 60)

importances = meta_model.feature_importances_
sorted_idx = np.argsort(importances)[::-1][:15]

for rank, idx in enumerate(sorted_idx, 1):
    print(f"  {rank:2d}. {feature_names[idx]:40s}  importance={importances[idx]:.4f}")

# ==========================
# 9. Save Meta-Learner Artifacts
# ==========================
print("\n" + "=" * 60)
print("💾 STAGE 8: Saving meta-learner artifacts")
print("=" * 60)

joblib.dump(meta_model,      os.path.join(META_DIR, "meta_label_model.joblib"))
joblib.dump(meta_imputer,    os.path.join(META_DIR, "meta_imputer.joblib"))
joblib.dump(meta_scaler,     os.path.join(META_DIR, "meta_scaler.joblib"))
joblib.dump(feature_names,   os.path.join(META_DIR, "meta_feature_names.joblib"))

print(f"  ✅ Saved to: {META_DIR}")
print(f"     meta_label_model.joblib   — Meta-learner XGBoost")
print(f"     meta_imputer.joblib       — Meta-feature imputer")
print(f"     meta_scaler.joblib        — Meta-feature scaler")
print(f"     meta_feature_names.joblib — Feature name list ({len(feature_names)} features)")
if tfidf_models:
    for name in tfidf_models:
        print(f"     tfidf_{name}.joblib   — TF-IDF for {name}")

print("\n" + "=" * 60)
print("🎉 TRAINING COMPLETE")
print("=" * 60)
print(f"""
Summary:
  Base model:  FROZEN (untouched in models/)
  Meta-learner: models/meta/meta_label_model.joblib
  Input:  base_model_probs + TVC features + spatial OCR TF-IDF
  CV F1:  {search.best_score_:.4f}

To use in the pipeline, load the meta-learner after the base model
prediction and feed it the combined feature vector.
""")
